/*
 * This file is generated by jOOQ.
 */
package com.yuqi.protocol.meta.tables.records;


import com.yuqi.protocol.meta.tables.Tables;
import org.jooq.Field;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TablesRecord extends TableRecordImpl<TablesRecord> implements Record22<String, String, String, String, String, ULong, String, ULong, ULong, ULong, ULong, ULong, ULong, ULong, LocalDateTime, LocalDateTime, LocalDateTime, String, ULong, String, String, Integer> {

    private static final long serialVersionUID = -1568717557;

    /**
     * Create a detached TablesRecord
     */
    public TablesRecord() {
        super(Tables.TABLES);
    }

    /**
     * Getter for <code>sloth.tables.TABLE_CATALOG</code>.
     */
    public String getTableCatalog() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sloth.tables.TABLE_SCHEMA</code>.
     */
    public void setTableSchema(String value) {
        set(1, value);
    }

    /**
     * Create a detached, initialised TablesRecord
     */
    public TablesRecord(String tableCatalog, String tableSchema, String tableName, String tableType, String engine, ULong version, String rowFormat, ULong tableRows, ULong avgRowLength, ULong dataLength, ULong maxDataLength, ULong indexLength, ULong dataFree, ULong autoIncrement, LocalDateTime createTime, LocalDateTime updateTime, LocalDateTime checkTime, String tableCollation, ULong checksum, String createOptions, String tableComment, Integer tableShard) {
        super(Tables.TABLES);

        set(0, tableCatalog);
        set(1, tableSchema);
        set(2, tableName);
        set(3, tableType);
        set(4, engine);
        set(5, version);
        set(6, rowFormat);
        set(7, tableRows);
        set(8, avgRowLength);
        set(9, dataLength);
        set(10, maxDataLength);
        set(11, indexLength);
        set(12, dataFree);
        set(13, autoIncrement);
        set(14, createTime);
        set(15, updateTime);
        set(16, checkTime);
        set(17, tableCollation);
        set(18, checksum);
        set(19, createOptions);
        set(20, tableComment);
        set(21, tableShard);
    }

    /**
     * Setter for <code>sloth.tables.TABLE_NAME</code>.
     */
    public void setTableName(String value) {
        set(2, value);
    }

    /**
     * Setter for <code>sloth.tables.TABLE_CATALOG</code>.
     */
    public void setTableCatalog(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sloth.tables.TABLE_SCHEMA</code>.
     */
    public String getTableSchema() {
        return (String) get(1);
    }

    /**
     * Getter for <code>sloth.tables.TABLE_TYPE</code>.
     */
    public String getTableType() {
        return (String) get(3);
    }

    /**
     * Getter for <code>sloth.tables.TABLE_NAME</code>.
     */
    public String getTableName() {
        return (String) get(2);
    }

    /**
     * Getter for <code>sloth.tables.ENGINE</code>.
     */
    public String getEngine() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sloth.tables.VERSION</code>.
     */
    public void setVersion(ULong value) {
        set(5, value);
    }

    /**
     * Setter for <code>sloth.tables.TABLE_TYPE</code>.
     */
    public void setTableType(String value) {
        set(3, value);
    }

    /**
     * Setter for <code>sloth.tables.ROW_FORMAT</code>.
     */
    public void setRowFormat(String value) {
        set(6, value);
    }

    /**
     * Setter for <code>sloth.tables.ENGINE</code>.
     */
    public void setEngine(String value) {
        set(4, value);
    }

    /**
     * Setter for <code>sloth.tables.TABLE_ROWS</code>.
     */
    public void setTableRows(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>sloth.tables.VERSION</code>.
     */
    public ULong getVersion() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>sloth.tables.AVG_ROW_LENGTH</code>.
     */
    public void setAvgRowLength(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>sloth.tables.ROW_FORMAT</code>.
     */
    public String getRowFormat() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sloth.tables.DATA_LENGTH</code>.
     */
    public void setDataLength(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>sloth.tables.TABLE_ROWS</code>.
     */
    public ULong getTableRows() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>sloth.tables.MAX_DATA_LENGTH</code>.
     */
    public void setMaxDataLength(ULong value) {
        set(10, value);
    }

    /**
     * Getter for <code>sloth.tables.AVG_ROW_LENGTH</code>.
     */
    public ULong getAvgRowLength() {
        return (ULong) get(8);
    }

    /**
     * Getter for <code>sloth.tables.DATA_LENGTH</code>.
     */
    public ULong getDataLength() {
        return (ULong) get(9);
    }

    /**
     * Getter for <code>sloth.tables.INDEX_LENGTH</code>.
     */
    public ULong getIndexLength() {
        return (ULong) get(11);
    }

    /**
     * Getter for <code>sloth.tables.MAX_DATA_LENGTH</code>.
     */
    public ULong getMaxDataLength() {
        return (ULong) get(10);
    }

    /**
     * Getter for <code>sloth.tables.DATA_FREE</code>.
     */
    public ULong getDataFree() {
        return (ULong) get(12);
    }

    /**
     * Setter for <code>sloth.tables.AUTO_INCREMENT</code>.
     */
    public void setAutoIncrement(ULong value) {
        set(13, value);
    }

    /**
     * Setter for <code>sloth.tables.INDEX_LENGTH</code>.
     */
    public void setIndexLength(ULong value) {
        set(11, value);
    }

    /**
     * Setter for <code>sloth.tables.CREATE_TIME</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Setter for <code>sloth.tables.DATA_FREE</code>.
     */
    public void setDataFree(ULong value) {
        set(12, value);
    }

    /**
     * Setter for <code>sloth.tables.UPDATE_TIME</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>sloth.tables.AUTO_INCREMENT</code>.
     */
    public ULong getAutoIncrement() {
        return (ULong) get(13);
    }

    /**
     * Setter for <code>sloth.tables.CHECK_TIME</code>.
     */
    public void setCheckTime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>sloth.tables.CREATE_TIME</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>sloth.tables.TABLE_COLLATION</code>.
     */
    public void setTableCollation(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>sloth.tables.UPDATE_TIME</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>sloth.tables.CHECKSUM</code>.
     */
    public void setChecksum(ULong value) {
        set(18, value);
    }

    /**
     * Getter for <code>sloth.tables.CHECK_TIME</code>.
     */
    public LocalDateTime getCheckTime() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>sloth.tables.CREATE_OPTIONS</code>.
     */
    public void setCreateOptions(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>sloth.tables.TABLE_COLLATION</code>.
     */
    public String getTableCollation() {
        return (String) get(17);
    }

    /**
     * Setter for <code>sloth.tables.TABLE_COMMENT</code>.
     */
    public void setTableComment(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>sloth.tables.CHECKSUM</code>.
     */
    public ULong getChecksum() {
        return (ULong) get(18);
    }

    /**
     * Getter for <code>sloth.tables.CREATE_OPTIONS</code>.
     */
    public String getCreateOptions() {
        return (String) get(19);
    }

    /**
     * Getter for <code>sloth.tables.TABLE_COMMENT</code>.
     */
    public String getTableComment() {
        return (String) get(20);
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>sloth.tables.TABLE_SHARD</code>. shard数目
     */
    public Integer getTableShard() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>sloth.tables.TABLE_SHARD</code>. shard数目
     */
    public void setTableShard(Integer value) {
        set(21, value);
    }

    @Override
    public Field<String> field1() {
        return Tables.TABLES.TABLE_CATALOG;
    }

    @Override
    public Field<String> field2() {
        return Tables.TABLES.TABLE_SCHEMA;
    }

    @Override
    public Field<String> field3() {
        return Tables.TABLES.TABLE_NAME;
    }

    @Override
    public Field<String> field4() {
        return Tables.TABLES.TABLE_TYPE;
    }

    @Override
    public Field<String> field5() {
        return Tables.TABLES.ENGINE;
    }

    @Override
    public Field<ULong> field6() {
        return Tables.TABLES.VERSION;
    }

    @Override
    public Field<String> field7() {
        return Tables.TABLES.ROW_FORMAT;
    }

    @Override
    public Field<ULong> field8() {
        return Tables.TABLES.TABLE_ROWS;
    }

    @Override
    public Field<ULong> field9() {
        return Tables.TABLES.AVG_ROW_LENGTH;
    }

    @Override
    public Field<ULong> field10() {
        return Tables.TABLES.DATA_LENGTH;
    }

    @Override
    public Field<ULong> field11() {
        return Tables.TABLES.MAX_DATA_LENGTH;
    }

    @Override
    public Field<ULong> field12() {
        return Tables.TABLES.INDEX_LENGTH;
    }

    @Override
    public Field<ULong> field13() {
        return Tables.TABLES.DATA_FREE;
    }

    @Override
    public Field<ULong> field14() {
        return Tables.TABLES.AUTO_INCREMENT;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return Tables.TABLES.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return Tables.TABLES.UPDATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return Tables.TABLES.CHECK_TIME;
    }

    @Override
    public Field<String> field18() {
        return Tables.TABLES.TABLE_COLLATION;
    }

    @Override
    public Field<ULong> field19() {
        return Tables.TABLES.CHECKSUM;
    }

    @Override
    public Field<String> field20() {
        return Tables.TABLES.CREATE_OPTIONS;
    }

    @Override
    public Field<String> field21() {
        return Tables.TABLES.TABLE_COMMENT;
    }

    @Override
    public Row22<String, String, String, String, String, ULong, String, ULong, ULong, ULong, ULong, ULong, ULong, ULong, LocalDateTime, LocalDateTime, LocalDateTime, String, ULong, String, String, Integer> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    public String component1() {
        return getTableCatalog();
    }

    @Override
    public String component2() {
        return getTableSchema();
    }

    @Override
    public String component3() {
        return getTableName();
    }

    @Override
    public String component4() {
        return getTableType();
    }

    @Override
    public String component5() {
        return getEngine();
    }

    @Override
    public ULong component6() {
        return getVersion();
    }

    @Override
    public String component7() {
        return getRowFormat();
    }

    @Override
    public ULong component8() {
        return getTableRows();
    }

    @Override
    public ULong component9() {
        return getAvgRowLength();
    }

    @Override
    public ULong component10() {
        return getDataLength();
    }

    @Override
    public ULong component11() {
        return getMaxDataLength();
    }

    @Override
    public ULong component12() {
        return getIndexLength();
    }

    @Override
    public ULong component13() {
        return getDataFree();
    }

    @Override
    public ULong component14() {
        return getAutoIncrement();
    }

    @Override
    public LocalDateTime component15() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component16() {
        return getUpdateTime();
    }

    @Override
    public LocalDateTime component17() {
        return getCheckTime();
    }

    @Override
    public String component18() {
        return getTableCollation();
    }

    @Override
    public ULong component19() {
        return getChecksum();
    }

    @Override
    public String component20() {
        return getCreateOptions();
    }

    @Override
    public String component21() {
        return getTableComment();
    }

    @Override
    public Row22<String, String, String, String, String, ULong, String, ULong, ULong, ULong, ULong, ULong, ULong, ULong, LocalDateTime, LocalDateTime, LocalDateTime, String, ULong, String, String, Integer> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    public String value1() {
        return getTableCatalog();
    }

    @Override
    public String value2() {
        return getTableSchema();
    }

    @Override
    public String value3() {
        return getTableName();
    }

    @Override
    public String value4() {
        return getTableType();
    }

    @Override
    public String value5() {
        return getEngine();
    }

    @Override
    public ULong value6() {
        return getVersion();
    }

    @Override
    public String value7() {
        return getRowFormat();
    }

    @Override
    public ULong value8() {
        return getTableRows();
    }

    @Override
    public ULong value9() {
        return getAvgRowLength();
    }

    @Override
    public ULong value10() {
        return getDataLength();
    }

    @Override
    public ULong value11() {
        return getMaxDataLength();
    }

    @Override
    public ULong value12() {
        return getIndexLength();
    }

    @Override
    public ULong value13() {
        return getDataFree();
    }

    @Override
    public ULong value14() {
        return getAutoIncrement();
    }

    @Override
    public LocalDateTime value15() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value16() {
        return getUpdateTime();
    }

    @Override
    public LocalDateTime value17() {
        return getCheckTime();
    }

    @Override
    public String value18() {
        return getTableCollation();
    }

    @Override
    public ULong value19() {
        return getChecksum();
    }

    @Override
    public String value20() {
        return getCreateOptions();
    }

    @Override
    public String value21() {
        return getTableComment();
    }

    @Override
    public Field<Integer> field22() {
        return Tables.TABLES.TABLE_SHARD;
    }

    @Override
    public TablesRecord value1(String value) {
        setTableCatalog(value);
        return this;
    }

    @Override
    public TablesRecord value2(String value) {
        setTableSchema(value);
        return this;
    }

    @Override
    public TablesRecord value3(String value) {
        setTableName(value);
        return this;
    }

    @Override
    public TablesRecord value4(String value) {
        setTableType(value);
        return this;
    }

    @Override
    public TablesRecord value5(String value) {
        setEngine(value);
        return this;
    }

    @Override
    public TablesRecord value6(ULong value) {
        setVersion(value);
        return this;
    }

    @Override
    public TablesRecord value7(String value) {
        setRowFormat(value);
        return this;
    }

    @Override
    public TablesRecord value8(ULong value) {
        setTableRows(value);
        return this;
    }

    @Override
    public TablesRecord value9(ULong value) {
        setAvgRowLength(value);
        return this;
    }

    @Override
    public TablesRecord value10(ULong value) {
        setDataLength(value);
        return this;
    }

    @Override
    public TablesRecord value11(ULong value) {
        setMaxDataLength(value);
        return this;
    }

    @Override
    public TablesRecord value12(ULong value) {
        setIndexLength(value);
        return this;
    }

    @Override
    public TablesRecord value13(ULong value) {
        setDataFree(value);
        return this;
    }

    @Override
    public TablesRecord value14(ULong value) {
        setAutoIncrement(value);
        return this;
    }

    @Override
    public TablesRecord value15(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TablesRecord value16(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TablesRecord value17(LocalDateTime value) {
        setCheckTime(value);
        return this;
    }

    @Override
    public TablesRecord value18(String value) {
        setTableCollation(value);
        return this;
    }

    @Override
    public TablesRecord value19(ULong value) {
        setChecksum(value);
        return this;
    }

    @Override
    public TablesRecord value20(String value) {
        setCreateOptions(value);
        return this;
    }

    @Override
    public TablesRecord value21(String value) {
        setTableComment(value);
        return this;
    }

    @Override
    public Integer component22() {
        return getTableShard();
    }

    @Override
    public Integer value22() {
        return getTableShard();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public TablesRecord value22(Integer value) {
        setTableShard(value);
        return this;
    }

    @Override
    public TablesRecord values(String value1, String value2, String value3, String value4, String value5, ULong value6, String value7, ULong value8, ULong value9, ULong value10, ULong value11, ULong value12, ULong value13, ULong value14, LocalDateTime value15, LocalDateTime value16, LocalDateTime value17, String value18, ULong value19, String value20, String value21, Integer value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }
}
