/*
 * This file is generated by jOOQ.
 */
package com.yuqi.protocol.meta.tables.pojos;


import org.jooq.types.ULong;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables implements Serializable {

    private static final long serialVersionUID = 1084508110;

    private String        tableCatalog;
    private String        tableSchema;
    private String        tableName;
    private String        tableType;
    private String        engine;
    private ULong         version;
    private String        rowFormat;
    private ULong         tableRows;
    private ULong         avgRowLength;
    private ULong         dataLength;
    private ULong         maxDataLength;
    private ULong         indexLength;
    private ULong         dataFree;
    private ULong         autoIncrement;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private LocalDateTime checkTime;
    private String        tableCollation;
    private ULong         checksum;
    private String        createOptions;
    private String        tableComment;

    public Tables() {}

    public Tables(Tables value) {
        this.tableCatalog = value.tableCatalog;
        this.tableSchema = value.tableSchema;
        this.tableName = value.tableName;
        this.tableType = value.tableType;
        this.engine = value.engine;
        this.version = value.version;
        this.rowFormat = value.rowFormat;
        this.tableRows = value.tableRows;
        this.avgRowLength = value.avgRowLength;
        this.dataLength = value.dataLength;
        this.maxDataLength = value.maxDataLength;
        this.indexLength = value.indexLength;
        this.dataFree = value.dataFree;
        this.autoIncrement = value.autoIncrement;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.checkTime = value.checkTime;
        this.tableCollation = value.tableCollation;
        this.checksum = value.checksum;
        this.createOptions = value.createOptions;
        this.tableComment = value.tableComment;
    }

    public Tables(
        String        tableCatalog,
        String        tableSchema,
        String        tableName,
        String        tableType,
        String        engine,
        ULong         version,
        String        rowFormat,
        ULong         tableRows,
        ULong         avgRowLength,
        ULong         dataLength,
        ULong         maxDataLength,
        ULong         indexLength,
        ULong         dataFree,
        ULong         autoIncrement,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        LocalDateTime checkTime,
        String        tableCollation,
        ULong         checksum,
        String        createOptions,
        String        tableComment
    ) {
        this.tableCatalog = tableCatalog;
        this.tableSchema = tableSchema;
        this.tableName = tableName;
        this.tableType = tableType;
        this.engine = engine;
        this.version = version;
        this.rowFormat = rowFormat;
        this.tableRows = tableRows;
        this.avgRowLength = avgRowLength;
        this.dataLength = dataLength;
        this.maxDataLength = maxDataLength;
        this.indexLength = indexLength;
        this.dataFree = dataFree;
        this.autoIncrement = autoIncrement;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.checkTime = checkTime;
        this.tableCollation = tableCollation;
        this.checksum = checksum;
        this.createOptions = createOptions;
        this.tableComment = tableComment;
    }

    public String getTableCatalog() {
        return this.tableCatalog;
    }

    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    public String getTableSchema() {
        return this.tableSchema;
    }

    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getTableType() {
        return this.tableType;
    }

    public void setTableType(String tableType) {
        this.tableType = tableType;
    }

    public String getEngine() {
        return this.engine;
    }

    public void setEngine(String engine) {
        this.engine = engine;
    }

    public ULong getVersion() {
        return this.version;
    }

    public void setVersion(ULong version) {
        this.version = version;
    }

    public String getRowFormat() {
        return this.rowFormat;
    }

    public void setRowFormat(String rowFormat) {
        this.rowFormat = rowFormat;
    }

    public ULong getTableRows() {
        return this.tableRows;
    }

    public void setTableRows(ULong tableRows) {
        this.tableRows = tableRows;
    }

    public ULong getAvgRowLength() {
        return this.avgRowLength;
    }

    public void setAvgRowLength(ULong avgRowLength) {
        this.avgRowLength = avgRowLength;
    }

    public ULong getDataLength() {
        return this.dataLength;
    }

    public void setDataLength(ULong dataLength) {
        this.dataLength = dataLength;
    }

    public ULong getMaxDataLength() {
        return this.maxDataLength;
    }

    public void setMaxDataLength(ULong maxDataLength) {
        this.maxDataLength = maxDataLength;
    }

    public ULong getIndexLength() {
        return this.indexLength;
    }

    public void setIndexLength(ULong indexLength) {
        this.indexLength = indexLength;
    }

    public ULong getDataFree() {
        return this.dataFree;
    }

    public void setDataFree(ULong dataFree) {
        this.dataFree = dataFree;
    }

    public ULong getAutoIncrement() {
        return this.autoIncrement;
    }

    public void setAutoIncrement(ULong autoIncrement) {
        this.autoIncrement = autoIncrement;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public LocalDateTime getCheckTime() {
        return this.checkTime;
    }

    public void setCheckTime(LocalDateTime checkTime) {
        this.checkTime = checkTime;
    }

    public String getTableCollation() {
        return this.tableCollation;
    }

    public void setTableCollation(String tableCollation) {
        this.tableCollation = tableCollation;
    }

    public ULong getChecksum() {
        return this.checksum;
    }

    public void setChecksum(ULong checksum) {
        this.checksum = checksum;
    }

    public String getCreateOptions() {
        return this.createOptions;
    }

    public void setCreateOptions(String createOptions) {
        this.createOptions = createOptions;
    }

    public String getTableComment() {
        return this.tableComment;
    }

    public void setTableComment(String tableComment) {
        this.tableComment = tableComment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tables (");

        sb.append(tableCatalog);
        sb.append(", ").append(tableSchema);
        sb.append(", ").append(tableName);
        sb.append(", ").append(tableType);
        sb.append(", ").append(engine);
        sb.append(", ").append(version);
        sb.append(", ").append(rowFormat);
        sb.append(", ").append(tableRows);
        sb.append(", ").append(avgRowLength);
        sb.append(", ").append(dataLength);
        sb.append(", ").append(maxDataLength);
        sb.append(", ").append(indexLength);
        sb.append(", ").append(dataFree);
        sb.append(", ").append(autoIncrement);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(checkTime);
        sb.append(", ").append(tableCollation);
        sb.append(", ").append(checksum);
        sb.append(", ").append(createOptions);
        sb.append(", ").append(tableComment);

        sb.append(")");
        return sb.toString();
    }
}
